config/routes.rb
Clidewatch::Application.routes.draw do

  resources :clides
  resources :ratings

  root :to => 'home#index'

end

app/models/clide.rb
class Clide < ActiveRecord::Base
  has_many :ratings

  attr_accessible :colaboration , :community , :floss    , :hosted  ,
                  :memory_hi    , :memory_lo , :name     , :private ,
                  :source       , :space_hi  , :space_lo , :ssh     ,
                  :ssl          , :sudo      , :url
  validates_presence_of :name
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :clide

  attr_accessible :clide_id  , :community , :debugging , :features    , :ip       ,
                  :lag       , :native    , :overall   , :performance , :pricing  ,
                  :stability , :support   , :web

  validates_presence_of :clide_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clides_controller.rb
class ClidesController < ApplicationController
  # GET /clides
  # GET /clides.json
  def index
    @clides = Clide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clides }
    end
  end

  # GET /clides/1
  # GET /clides/1.json
  def show
    @clide = Clide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clide }
    end
  end

  # GET /clides/new
  # GET /clides/new.json
  def new
    @clide = Clide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clide }
    end
  end

  # GET /clides/1/edit
  def edit
    @clide = Clide.find(params[:id])
  end

  # POST /clides
  # POST /clides.json
  def create
    @clide = Clide.new(params[:clide])

    respond_to do |format|
      if @clide.save
        format.html { redirect_to @clide, notice: 'Clide was successfully created.' }
        format.json { render json: @clide, status: :created, location: @clide }
      else
        format.html { render action: "new" }
        format.json { render json: @clide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clides/1
  # PUT /clides/1.json
  def update
    @clide = Clide.find(params[:id])

    respond_to do |format|
      if @clide.update_attributes(params[:clide])
        format.html { redirect_to @clide, notice: 'Clide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clides/1
  # DELETE /clides/1.json
  def destroy
    @clide = Clide.find(params[:id])
    @clide.destroy

    respond_to do |format|
      format.html { redirect_to clides_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index ; respond_to do | format | ; format.html ; end ; end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def index
    @ratings = []

    Clide.all.each do | a_clide |
      web         = n_webs         = native    = n_natives     = stability = n_stabilities =
      performance = n_performances = lag       = n_lags        = features  = n_featuress   =
      debugging   = n_debuggings   = community = n_communities = support   = n_supports    =
      pricing     = n_pricings     = overall   = n_overalls    = 0

      a_clide.ratings.all.each do | a_rating |
        web        += a_rating.web         and n_webs         += 1 if a_rating.web
        native     += a_rating.native      and n_natives      += 1 if a_rating.native
        stability  += a_rating.stability   and n_stabilities  += 1 if a_rating.stability
        performance+= a_rating.performance and n_performances += 1 if a_rating.performance
        lag        += a_rating.lag         and n_lags         += 1 if a_rating.lag
        features   += a_rating.features    and n_featuress    += 1 if a_rating.features
        debugging  += a_rating.debugging   and n_debuggings   += 1 if a_rating.debugging
        community  += a_rating.community   and n_communities  += 1 if a_rating.community
        support    += a_rating.support     and n_supports     += 1 if a_rating.support
        pricing    += a_rating.pricing     and n_pricings     += 1 if a_rating.pricing
        overall    += a_rating.overall     and n_overalls     += 1 if a_rating.overall
      end

      web         /= n_webs        .to_f unless n_webs        .zero?
      native      /= n_natives     .to_f unless n_natives     .zero?
      stability   /= n_stabilities .to_f unless n_stabilities .zero?
      performance /= n_performances.to_f unless n_performances.zero?
      lag         /= n_lags        .to_f unless n_lags        .zero?
      features    /= n_featuress   .to_f unless n_featuress   .zero?
      debugging   /= n_debuggings  .to_f unless n_debuggings  .zero?
      community   /= n_communities .to_f unless n_communities .zero?
      support     /= n_supports    .to_f unless n_supports    .zero?
      pricing     /= n_pricings    .to_f unless n_pricings    .zero?
      overall     /= n_overalls    .to_f unless n_overalls    .zero?

      @ratings <<
      {
        :name        => a_clide.name ,
        :web         => web          ,
        :native      => native       ,
        :stability   => stability    ,
        :performance => performance  ,
        :lag         => lag          ,
        :features    => features     ,
        :debugging   => debugging    ,
        :community   => community    ,
        :support     => support      ,
        :pricing     => pricing      ,
        :overall     => overall
      }
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  def new
    @rating = Rating.new
    @clides = Clide.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  def edit
    @rating = Rating.find(params[:id])
  end

  def create
    @rating    = Rating.new(params[:rating])
    @rating.ip = request.remote_ip

    respond_to do |format|
      if @rating.save
        format.html { redirect_to ratings_url , notice: 'Rating was successfully created.' }
        format.json { render json: @rating , status: :created , location: @rating }
      else
        format.html { @clides = Clide.all ; render action: "new" }
        format.json { render json: @rating.errors , status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clides_helper.rb
module ClidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/clides/_form.html.erb
<%= form_for(@clide) do |f| %>
  <% if @clide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clide.errors.count, "error") %> prohibited this clide from being saved:</h2>

      <ul>
      <% @clide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :memory_lo %><br />
    <%= f.number_field :memory_lo %>
  </div>
  <div class="field">
    <%= f.label :memory_hi %><br />
    <%= f.number_field :memory_hi %>
  </div>
  <div class="field">
    <%= f.label :space_lo %><br />
    <%= f.number_field :space_lo %>
  </div>
  <div class="field">
    <%= f.label :space_hi %><br />
    <%= f.number_field :space_hi %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :colaboration %><br />
    <%= f.check_box :colaboration %>
  </div>
  <div class="field">
    <%= f.label :community %><br />
    <%= f.check_box :community %>
  </div>
  <div class="field">
    <%= f.label :sudo %><br />
    <%= f.check_box :sudo %>
  </div>
  <div class="field">
    <%= f.label :ssh %><br />
    <%= f.check_box :ssh %>
  </div>
  <div class="field">
    <%= f.label :ssl %><br />
    <%= f.check_box :ssl %>
  </div>
  <div class="field">
    <%= f.label :hosted %><br />
    <%= f.check_box :hosted %>
  </div>
  <div class="field">
    <%= f.label :floss %><br />
    <%= f.text_field :floss %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clides/edit.html.erb
<h1>Editing clide</h1>

<%= render 'form' %>

<%= link_to 'Show', @clide %> |
<%= link_to 'Back', clides_path %>

app/views/clides/index.html.erb
  <table id="clidesTable">
    <tr>
      <th>Name</th>
      <th>Memory</th>
      <th>Disk</th>
      <th>Private</th>
      <th>Colaboration</th>
      <th>Community</th>
      <th>Sudo</th>
      <th>Ssh</th>
      <th>Ssl</th>
      <th>Hosted</th>
      <th>Source</th>
<% if @is_admin %>
      <th></th><th></th><th></th>
<% end %>
    </tr>

<%
  def yes_or_no a_bool ; (a_bool == !!a_bool)? ((a_bool)? "yes" : "no") : "?" ; end ;
  def parse_range an_int , another_int
    (!an_int     .is_a? Fixnum) ? "?" :
    (!another_int.is_a? Fixnum) ? "?" :
    (an_int == -1)              ? "∞"         :
    (an_int == another_int)     ? "#{an_int}" : "#{an_int}-#{another_int}"
  end

  @clides.each do |clide|
%>
    <tr>
      <td><%= link_to     clide.name ,      clide.url , :target => '_blank'    %></td>
      <td><%= parse_range clide.memory_lo , clide.memory_hi                    %></td>
      <td><%= parse_range clide.space_lo ,  clide.space_hi                     %></td>
      <td><%= yes_or_no   clide.private                                        %></td>
      <td><%= yes_or_no   clide.colaboration                                   %></td>
      <td><%= yes_or_no   clide.community                                      %></td>
      <td><%= yes_or_no   clide.sudo                                           %></td>
      <td><%= yes_or_no   clide.ssh                                            %></td>
      <td><%= yes_or_no   clide.ssl                                            %></td>
      <td><%= yes_or_no   clide.hosted                                         %></td>
  <% unless clide.source.blank? %>
      <td><%= link_to     clide.floss ,     clide.source , :target => '_blank' %></td>
  <% else %>
      <td><%= clide.source                                                     %></td>
  <% end %>
  <% if @is_admin %>
      <td><%= link_to 'Show' , clide %></td>
      <td><%= link_to 'Edit' , edit_clide_path(clide) %></td>
      <td><%= link_to 'Destroy' , clide , :method => :delete , :data => { confirm: 'Are you sure?' } %></td>
  <% end %>
    </tr>
<% end %>
  </table>

  <br />

<%= link_to 'New Clide', new_clide_path if @is_admin %>

app/views/clides/new.html.erb
<h1>New clide</h1>

<%= render 'form' %>

<%= link_to 'Back', clides_path %>

app/views/clides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @clide.name %>
</p>

<p>
  <b>Url:</b>
  <%= @clide.url %>
</p>

<p>
  <b>Memory lo:</b>
  <%= @clide.memory_lo %>
</p>

<p>
  <b>Memory hi:</b>
  <%= @clide.memory_hi %>
</p>

<p>
  <b>Space lo:</b>
  <%= @clide.space_lo %>
</p>

<p>
  <b>Space hi:</b>
  <%= @clide.space_hi %>
</p>

<p>
  <b>Private:</b>
  <%= @clide.private %>
</p>

<p>
  <b>Colaboration:</b>
  <%= @clide.colaboration %>
</p>

<p>
  <b>Community:</b>
  <%= @clide.community %>
</p>

<p>
  <b>Sudo:</b>
  <%= @clide.sudo %>
</p>

<p>
  <b>Ssh:</b>
  <%= @clide.ssh %>
</p>

<p>
  <b>Ssl:</b>
  <%= @clide.ssl %>
</p>

<p>
  <b>Hosted:</b>
  <%= @clide.hosted %>
</p>

<p>
  <b>Floss:</b>
  <%= @clide.floss %>
</p>

<p>
  <b>Source:</b>
  <%= @clide.source %>
</p>


<%= link_to 'Edit', edit_clide_path(@clide) %> |
<%= link_to 'Back', clides_path %>

app/views/home/index.html.erb
<% content_for :header do %>

<table id="headerTable">

  <tr>
    <td id="bannerTd">
      <pre id="asciiBannerPre"><%= ASCII_ART_BANNERS[0] %></pre>
      <span id="siteDescSpan">
          <%=raw '<b           id="promptLoginB"    >clide@guide</b>'      +
                 '<span        id="promptPathSpan"  >:~/cloud/ide/</span>' +
                 '$ watch<span id="promptCursorSpan">_</span>'             %></span>
    </td>
    <td id="headerRTd">
      <span id="headerSpan">
        <%= link_to "Rate the clIDEs you've tried" , 'ratings' %></span></td>
  </tr>
</table>

<% end %>


<table id="contentTable">
  <tr>
    <td id="navTd">
      <table id="navTable">
        <tr><td onClick="parent.contentFrame.location = 'clides'"   >Stats</td   ></tr>
        <tr><td onClick="parent.contentFrame.location = 'ratings'"  >Ratingss</td></tr>
        <tr><td onClick="parent.contentFrame.location = 'reviews'"  >Reviewss</td></tr>
        <tr><td onClick="parent.contentFrame.location = 'faqs.html'">FAQs</td    ></tr>
      </table>
    </td>
    <td id="contentTd"><iframe id="contentFrame" src="welcome.html"></iframe></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>_Cl_IDE_guide_</title>
  <%= stylesheet_link_tag    "application" , :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="presentationDiv">

  <%= yield %>

</div>


</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClIDEwatch</title>
  <%= stylesheet_link_tag    "application" , :media => "all" %>
  <%= stylesheet_link_tag    "home"        , :media => "all" %>
  <%= javascript_include_tag "home"                          %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="headerDiv" ><%= yield :header %></div>

<div id="contentDiv"><%= yield         %></div>


</body>
</html>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

Cast your vote -->
<%= button_to  "Vote" , new_rating_path , :method => "get" %>

<table id="ratingsTable">
  <tr>
    <th>clIDE</th>
    <th>Web</th>
    <th>Native</th>
    <th>Stability</th>
    <th>Performance</th>
    <th>Lag</th>
    <th>Features</th>
    <th>Debugging</th>
    <th>Community</th>
    <th>Support</th>
    <th>Pricing</th>
    <th>Overall</th>
  </tr>

<% @ratings.each do | a_rating | %>
  <tr>
    <td><%= sprintf "%s"  , a_rating[:name]        %></td>
    <td><%= sprintf "%.1f" , a_rating[:web]         %></td>
    <td><%= sprintf "%.1f" , a_rating[:native]      %></td>
    <td><%= sprintf "%.1f" , a_rating[:stability]   %></td>
    <td><%= sprintf "%.1f" , a_rating[:performance] %></td>
    <td><%= sprintf "%.1f" , a_rating[:lag]         %></td>
    <td><%= sprintf "%.1f" , a_rating[:features]    %></td>
    <td><%= sprintf "%.1f" , a_rating[:debugging]   %></td>
    <td><%= sprintf "%.1f" , a_rating[:community]   %></td>
    <td><%= sprintf "%.1f" , a_rating[:support]     %></td>
    <td><%= sprintf "%.1f" , a_rating[:pricing]     %></td>
    <td><%= sprintf "%.1f" , a_rating[:overall]     %></td>
  </tr>
<% end%>

</table>

app/views/ratings/new.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited your votes from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Rate a clIDE you've tried
    <%= select_tag "rating[clide_id]" , options_from_collection_for_select(@clides , "id" , "name") ,
                  :prompt   => "Select a clIDE" ,
                  :onchange => "var submitBtn      = document.getElementById('ratingSubmitInput') ;" +
                                "submitBtn.disabled = !this.value ;" %>
  </h3>
  You can vote for as many or as few categories as you like.

  <table id="ratingsTable">
    <tr><th>Criteria</th><th>poor</th><th>&lt;-</th><th>ok</th><th>-&gt;</th><th>superb</th></tr>

    <tr>
      <td>Web Development (rails,php,node,etc)</td>
      <td><%= f.radio_button :web , 1 , :checked => false %></td>
      <td><%= f.radio_button :web , 2 , :checked => false %></td>
      <td><%= f.radio_button :web , 3 , :checked => false %></td>
      <td><%= f.radio_button :web , 4 , :checked => false %></td>
      <td><%= f.radio_button :web , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Native Development (C,java,etc)</td>
      <td><%= f.radio_button :native , 1 , :checked => false %></td>
      <td><%= f.radio_button :native , 2 , :checked => false %></td>
      <td><%= f.radio_button :native , 3 , :checked => false %></td>
      <td><%= f.radio_button :native , 4 , :checked => false %></td>
      <td><%= f.radio_button :native , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Stability / Uptime</td>
      <td><%= f.radio_button :stability , 1 , :checked => false %></td>
      <td><%= f.radio_button :stability , 2 , :checked => false %></td>
      <td><%= f.radio_button :stability , 3 , :checked => false %></td>
      <td><%= f.radio_button :stability , 4 , :checked => false %></td>
      <td><%= f.radio_button :stability , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Performance</td>
      <td><%= f.radio_button :performance , 1 , :checked => false %></td>
      <td><%= f.radio_button :performance , 2 , :checked => false %></td>
      <td><%= f.radio_button :performance , 3 , :checked => false %></td>
      <td><%= f.radio_button :performance , 4 , :checked => false %></td>
      <td><%= f.radio_button :performance , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Responsiveness / Lag</td>
      <td><%= f.radio_button :lag , 1 , :checked => false %></td>
      <td><%= f.radio_button :lag , 2 , :checked => false %></td>
      <td><%= f.radio_button :lag , 3 , :checked => false %></td>
      <td><%= f.radio_button :lag , 4 , :checked => false %></td>
      <td><%= f.radio_button :lag , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Available Features</td>
      <td><%= f.radio_button :features , 1 , :checked => false %></td>
      <td><%= f.radio_button :features , 2 , :checked => false %></td>
      <td><%= f.radio_button :features , 3 , :checked => false %></td>
      <td><%= f.radio_button :features , 4 , :checked => false %></td>
      <td><%= f.radio_button :features , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Debugging Tools</td>
      <td><%= f.radio_button :debugging , 1 , :checked => false %></td>
      <td><%= f.radio_button :debugging , 2 , :checked => false %></td>
      <td><%= f.radio_button :debugging , 3 , :checked => false %></td>
      <td><%= f.radio_button :debugging , 4 , :checked => false %></td>
      <td><%= f.radio_button :debugging , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Community Interaction</td>
      <td><%= f.radio_button :community , 1 , :checked => false %></td>
      <td><%= f.radio_button :community , 2 , :checked => false %></td>
      <td><%= f.radio_button :community , 3 , :checked => false %></td>
      <td><%= f.radio_button :community , 4 , :checked => false %></td>
      <td><%= f.radio_button :community , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Technical Support</td>
      <td><%= f.radio_button :support , 1 , :checked => false %></td>
      <td><%= f.radio_button :support , 2 , :checked => false %></td>
      <td><%= f.radio_button :support , 3 , :checked => false %></td>
      <td><%= f.radio_button :support , 4 , :checked => false %></td>
      <td><%= f.radio_button :support , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Value / Pricing</td>
      <td><%= f.radio_button :pricing , 1 , :checked => false %></td>
      <td><%= f.radio_button :pricing , 2 , :checked => false %></td>
      <td><%= f.radio_button :pricing , 3 , :checked => false %></td>
      <td><%= f.radio_button :pricing , 4 , :checked => false %></td>
      <td><%= f.radio_button :pricing , 5 , :checked => false %></td>
    </tr>
    <tr>
      <td>Overall Rating</td>
      <td><%= f.radio_button :overall , 1 , :checked => false %></td>
      <td><%= f.radio_button :overall , 2 , :checked => false %></td>
      <td><%= f.radio_button :overall , 3 , :checked => false %></td>
      <td><%= f.radio_button :overall , 4 , :checked => false %></td>
      <td><%= f.radio_button :overall , 5 , :checked => false %></td>
    </tr>
  </table>

  <div class="actions">
    <%= button_to  "Cancel" , ratings_path , :method => "get" %>
    <%= submit_tag "Vote"   , :id => 'ratingSubmitInput' , :disabled => true %>
  </div>

<% end %>